/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mJuvOQnVwqa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function timelineExperience() {
  return (
    <div className="p-6 sm:p-10">
      <div className="after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 relative pl-6 after:left-0 grid gap-10">
        <div className="grid grid-cols-[auto,1fr] gap-1 text-sm relative items-center">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <div className="px-2 py-1 bg-black text-white rounded-md text-xs font-medium">2021 - Present</div>
          <div className="font-medium">PhD Candidate in Physics at Massachusetts Institute of Technology</div>
          <div className="col-start-2 text-muted-foreground pl-6">
            <ul className="list-none pl-4">
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Pursuing a PhD in Physics with a focus on Astrophysics.
              </li>
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Expected graduation in 2026.
              </li>
            </ul>
          </div>
        </div>
        <div className="grid grid-cols-[auto,1fr] gap-1 text-sm relative items-center">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <div className="px-2 py-1 bg-black text-white rounded-md text-xs font-medium">May 2021</div>
          <div className="font-medium">Bachelor of Science in Physics from Missouri State University</div>
          <div className="col-start-2 text-muted-foreground pl-6">
            <ul className="list-none pl-4">
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Graduated with a Bachelor of Science in Physics, with an emphasis in Astronomy and Astrophysics.
              </li>
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Completed a minor in Mathematics.
              </li>
            </ul>
          </div>
        </div>
        <div className="grid grid-cols-[auto,1fr] gap-1 text-sm relative items-center">
          <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
          <div className="px-2 py-1 bg-black text-white rounded-md text-xs font-medium">2020 - 2021</div>
          <div className="font-medium">Computational Science Certificate</div>
          <div className="col-start-2 text-muted-foreground pl-6">
            <ul className="list-none pl-4">
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Completed a Computational Science Certificate program.
              </li>
              <li className="flex items-start">
                <StarIcon className="h-4 w-4 mr-2 fill-primary" />
                Focused on advanced computational techniques and their applications in scientific research.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
